package com.poworkspace.appModule;

import com.poworkspace.view.InitiatableProcessVOImpl;
import com.poworkspace.view.TaskListVOImpl;

import java.util.List;

import oracle.jbo.server.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 08 14:24:52 IST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class POWorkspaceAppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public POWorkspaceAppModuleImpl() {
    }

    /**
     * Container's getter for TaskListVO1.
     * @return TaskListVO1
     */
    public TaskListVOImpl getTaskListVO1() {
        return (TaskListVOImpl) findViewObject("TaskListVO1");
    }

    /**
     * Container's getter for InitiatableProcessVO1.
     * @return InitiatableProcessVO1
     */
    public InitiatableProcessVOImpl getInitiatableProcessVO1() {
        return (InitiatableProcessVOImpl) findViewObject("InitiatableProcessVO1");
    }
}

