CREATE TABLE CONTRACT_DOCUMENT 
(
  CONTRACT_ID VARCHAR2(50 BYTE) NOT NULL 
, CONTRACT_DOC BLOB 
, FILE_NAME VARCHAR2(4000 BYTE) 
, CONSTRAINT SYS_C009875 PRIMARY KEY 
  (
    CONTRACT_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX SYS_C009875 ON CONTRACT_DOCUMENT (CONTRACT_ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
LOB (CONTRACT_DOC) STORE AS SYS_LOB0000093154C00002$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  NOCACHE 
  LOGGING 
  TABLESPACE USERS 
  STORAGE 
  ( 
    INITIAL 106496 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS UNLIMITED 
    BUFFER_POOL DEFAULT 
  )  
);
