package model.common;

import java.sql.Date;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 01 12:18:17 IST 2015
// ---------------------------------------------------------------------
public interface ContractAM extends ApplicationModule {
    String getDateDifference(Date d1, Date d2);
}

